import 'package:flutter/material.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  // Placeholder text for the Terms of Service content
  static const String _termsContent = """
**1. Acceptance of Terms**
Welcome to the Nutri Recom app, a research project by the University of Oulu. By creating an account and using this application ("App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.

**2. Description of Service**
This App provides personalized food recommendations and explanations as part of an academic research study. The service is provided for informational and research purposes only and is not a substitute for professional medical or dietary advice.

**3. User Consent for Research**
By using this App, you acknowledge and agree that:
- The data you provide (profile, preferences, and feedback) will be collected and used for academic research purposes.
- The data will be anonymized and aggregated before any analysis or publication of research findings.
- Your participation is voluntary. You can stop using the App and request the deletion of your data at any time by contacting the research team.

**4. User Responsibilities**
You agree to provide accurate and current information during the onboarding process. You are responsible for maintaining the confidentiality of your account and password.

**5. Limitation of Liability**
The recommendations provided by this App are generated by an AI model and are for informational purposes only. The University of Oulu and the research team are not liable for any health-related issues, allergic reactions, or other consequences resulting from the use of the information provided by this App. Always consult with a qualified healthcare professional for personal dietary advice.

**6. Termination**
We may terminate or suspend your access to the App at any time, without prior notice or liability, for any reason, including if you breach these Terms.
""";
  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final ColorScheme colorScheme = theme.colorScheme;

    return Scaffold(
      backgroundColor: colorScheme.surface,
      appBar: AppBar(
        title: Text(
          'Terms of Service',
          style: theme.textTheme.headlineMedium
              ?.copyWith(color: colorScheme.onSurface),
        ),
        backgroundColor:
            theme.appBarTheme.backgroundColor ?? colorScheme.surface,
        elevation: theme.appBarTheme.elevation ?? 0,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                // i. Effective Date
                Text(
                  "Effective Date: May 23, 2025",
                  style: theme.textTheme.bodySmall?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: colorScheme.onSurfaceVariant,
                  ),
                ),
                const SizedBox(height: 16.0),

                // iii. Main Policy Content
                _buildStyledText(_termsContent, context),

                const SizedBox(height: 24.0),

                // vi. Back to Settings Button
                OutlinedButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  style: OutlinedButton.styleFrom(
                    foregroundColor: colorScheme.primary,
                    padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 24.0),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                    side: BorderSide(color: colorScheme.outline),
                  ),
                  child: const Text('← Back to Settings'),
                ),
                const SizedBox(height: 16.0), // Bottom padding
              ],
            ),
          ),
        ),
      ),
    );
  }

  // A helper method to parse text with simple markdown-like bolding (**text**).
  Widget _buildStyledText(String rawText, BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    // Style for regular text
    final defaultStyle = theme.textTheme.bodyMedium?.copyWith(
      color: colorScheme.onSurface,
      height: 1.5, // Improves readability of long paragraphs
    );
    // Style for headings (bolded text)
    final boldStyle = theme.textTheme.titleMedium?.copyWith(
      color: colorScheme.onSurface,
      fontWeight: FontWeight.bold,
    );

    final List<TextSpan> children = [];
    // This regex finds text enclosed in double asterisks.
    final RegExp regExp = RegExp(r'\*\*(.*?)\*\*');

    int lastMatchEnd = 0;
    for (final Match match in regExp.allMatches(rawText)) {
      // Add text before the match with default style
      if (match.start > lastMatchEnd) {
        children.add(TextSpan(
          text: rawText.substring(lastMatchEnd, match.start),
          style: defaultStyle,
        ));
      }

      // Add the matched (bold) text, using group 1 to get text inside asterisks
      children.add(TextSpan(
        text: match.group(1),
        style: boldStyle,
      ));

      lastMatchEnd = match.end;
    }

    // Add any remaining text after the last match
    if (lastMatchEnd < rawText.length) {
      children.add(TextSpan(
        text: rawText.substring(lastMatchEnd),
        style: defaultStyle,
      ));
    }

    return RichText(
      text: TextSpan(children: children),
    );
  }
}