import 'package:flutter/material.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  // Updated content based on "Terms of Service"
  static const String _termsContent = """
**1. Acceptance of Terms**
Welcome to NutriRecom. By creating an account and using this application ("App"), you agree to be bound by these Terms of Service. This App is a non-commercial academic research project conducted by researchers at the University of Oulu.

**2. Non-Commercial & Research Use**
The NutriRecom App is provided free of charge for academic research purposes. It contains no advertisements or in-app purchases. By using the App, you acknowledge that anonymized data regarding your food choices and preferences may be used for scientific analysis and publication.

**3. Medical Disclaimer (Important)**
**The App does not provide medical advice.** The recommendations generated by our AI system are for informational and educational purposes only. They are not intended to diagnose, treat, cure, or prevent any disease. Always consult with a qualified healthcare professional before making significant changes to your diet, especially if you have pre-existing health conditions.

**4. User Accounts**
You must be at least 18 years old to use this App. You are responsible for maintaining the confidentiality of your login credentials. You agree to provide accurate information regarding your dietary preferences to ensure the App functions correctly.

**5. Data Privacy**
Your use of the App is also governed by our **Privacy Notice**, which explains how we collect, safeguard, and process your data in compliance with the GDPR. By using the App, you consent to the data practices described therein.

**6. Limitation of Liability**
To the fullest extent permitted by law, the University of Oulu and the research team shall not be liable for any indirect, incidental, or consequential damages arising out of your use of the App or reliance on any information provided by the AI.

**7. Termination**
We reserve the right to suspend or terminate your account at any time, particularly if these Terms are violated or if the research project concludes.

**8. Contact Us**
If you have questions about these Terms, please contact the research team:
**Email:** amir.mollazadeh@oulu.fi & mehrdad.rostami@oulu.fi
""";

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final ColorScheme colorScheme = theme.colorScheme;

    return Scaffold(
      backgroundColor: colorScheme.surface,
      appBar: AppBar(
        title: Text(
          'Terms of Service',
          style: theme.textTheme.headlineMedium
              ?.copyWith(color: colorScheme.onSurface),
        ),
        backgroundColor:
            theme.appBarTheme.backgroundColor ?? colorScheme.surface,
        elevation: theme.appBarTheme.elevation ?? 0,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                // i. Effective Date
                Text(
                  "Last Updated: December 16, 2025",
                  style: theme.textTheme.bodySmall?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: colorScheme.onSurfaceVariant,
                  ),
                ),
                const SizedBox(height: 16.0),

                // iii. Main Policy Content
                _buildStyledText(_termsContent, context),

                const SizedBox(height: 24.0),

                // vi. Back to Settings Button
                OutlinedButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  style: OutlinedButton.styleFrom(
                    foregroundColor: colorScheme.primary,
                    padding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 24.0),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                    side: BorderSide(color: colorScheme.outline),
                  ),
                  child: const Text('← Back to Settings'),
                ),
                const SizedBox(height: 16.0), // Bottom padding
              ],
            ),
          ),
        ),
      ),
    );
  }

  // A helper method to parse text with simple markdown-like bolding (**text**).
  Widget _buildStyledText(String rawText, BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    // Style for regular text
    final defaultStyle = theme.textTheme.bodyMedium?.copyWith(
      color: colorScheme.onSurface,
      height: 1.5, // Improves readability of long paragraphs
    );
    // Style for headings (bolded text)
    final boldStyle = theme.textTheme.titleMedium?.copyWith(
      color: colorScheme.onSurface,
      fontWeight: FontWeight.bold,
    );

    final List<TextSpan> children = [];
    // This regex finds text enclosed in double asterisks.
    final RegExp regExp = RegExp(r'\*\*(.*?)\*\*');

    int lastMatchEnd = 0;
    for (final Match match in regExp.allMatches(rawText)) {
      // Add text before the match with default style
      if (match.start > lastMatchEnd) {
        children.add(TextSpan(
          text: rawText.substring(lastMatchEnd, match.start),
          style: defaultStyle,
        ));
      }

      // Add the matched (bold) text, using group 1 to get text inside asterisks
      children.add(TextSpan(
        text: match.group(1),
        style: boldStyle,
      ));

      lastMatchEnd = match.end;
    }

    // Add any remaining text after the last match
    if (lastMatchEnd < rawText.length) {
      children.add(TextSpan(
        text: rawText.substring(lastMatchEnd),
        style: defaultStyle,
      ));
    }

    return RichText(
      text: TextSpan(children: children),
    );
  }
}